import React from "react";
import { Dropdown } from "semantic-ui-react";

const materialOptions = [
  { key: "VACUUM", text: "VACUUM", value: "VACUUM" },
  { key: "HYDROGEN", text: "HYDROGEN", value: "HYDROGEN" },
  { key: "HELIUM", text: "HELIUM", value: "HELIUM" },
  { key: "LITHIUM", text: "LITHIUM", value: "LITHIUM" },
  { key: "BERYLLIUM", text: "BERYLLIUM", value: "BERYLLIUM" },
  { key: "BORON", text: "BORON", value: "BORON" },
  { key: "CARBON", text: "CARBON", value: "CARBON" },
  { key: "NITROGEN", text: "NITROGEN", value: "NITROGEN" },
  { key: "OXYGEN", text: "OXYGEN", value: "OXYGEN" },
  { key: "FLUORINE", text: "FLUORINE", value: "FLUORINE" },
  { key: "NEON", text: "NEON", value: "NEON" },
  { key: "SODIUM", text: "SODIUM", value: "SODIUM" },
  { key: "MAGNESIUM", text: "MAGNESIUM", value: "MAGNESIUM" },
  { key: "ALUMINIUM", text: "ALUMINIUM", value: "ALUMINIUM" },
  { key: "SILICON", text: "SILICON", value: "SILICON" },
  { key: "PHOSPHORUS", text: "PHOSPHORUS", value: "PHOSPHORUS" },
  { key: "SULFUR", text: "SULFUR", value: "SULFUR" },
  { key: "CHLORINE", text: "CHLORINE", value: "CHLORINE" },
  { key: "ARGON", text: "ARGON", value: "ARGON" },
  { key: "POTASSIUM", text: "POTASSIUM", value: "POTASSIUM" },
  { key: "CALCIUM", text: "CALCIUM", value: "CALCIUM" },
  { key: "SCANDIUM", text: "SCANDIUM", value: "SCANDIUM" },
  { key: "TITANIUM", text: "TITANIUM", value: "TITANIUM" },
  { key: "VANADIUM", text: "VANADIUM", value: "VANADIUM" },
  { key: "CHROMIUM", text: "CHROMIUM", value: "CHROMIUM" },
  { key: "MANGANESE", text: "MANGANESE", value: "MANGANESE" },
  { key: "IRON", text: "IRON", value: "IRON" },
  { key: "COBALT", text: "COBALT", value: "COBALT" },
  { key: "NICKEL", text: "NICKEL", value: "NICKEL" },
  { key: "COPPER", text: "COPPER", value: "COPPER" },
  { key: "ZINC", text: "ZINC", value: "ZINC" },
  { key: "GALLIUM", text: "GALLIUM", value: "GALLIUM" },
  { key: "GERMANIUM", text: "GERMANIUM", value: "GERMANIUM" },
  { key: "ARSENIC", text: "ARSENIC", value: "ARSENIC" },
  { key: "SELENIUM", text: "SELENIUM", value: "SELENIUM" },
  { key: "BROMINE", text: "BROMINE", value: "BROMINE" },
  { key: "KRYPTON", text: "KRYPTON", value: "KRYPTON" },
  { key: "RUBIDIUM", text: "RUBIDIUM", value: "RUBIDIUM" },
  { key: "STRONTIUM", text: "STRONTIUM", value: "STRONTIUM" },
  { key: "YTTRIUM", text: "YTTRIUM", value: "YTTRIUM" },
  { key: "ZIRCONIUM", text: "ZIRCONIUM", value: "ZIRCONIUM" },
  { key: "NIOBIUM", text: "NIOBIUM", value: "NIOBIUM" },
  { key: "MOLYBDENUM", text: "MOLYBDENUM", value: "MOLYBDENUM" },
  { key: "TECHNETIUM", text: "TECHNETIUM", value: "TECHNETIUM" },
  { key: "RUTHENIUM", text: "RUTHENIUM", value: "RUTHENIUM" },
  { key: "RHODIUM", text: "RHODIUM", value: "RHODIUM" },
  { key: "PALLADIUM", text: "PALLADIUM", value: "PALLADIUM" },
  { key: "SILVER", text: "SILVER", value: "SILVER" },
  { key: "CADMIUM", text: "CADMIUM", value: "CADMIUM" },
  { key: "INDIUM", text: "INDIUM", value: "INDIUM" },
  { key: "TIN", text: "TIN", value: "TIN" },
  { key: "ANTIMONY", text: "ANTIMONY", value: "ANTIMONY" },
  { key: "TELLURIUM", text: "TELLURIUM", value: "TELLURIUM" },
  { key: "IODINE", text: "IODINE", value: "IODINE" },
  { key: "XENON", text: "XENON", value: "XENON" },
  { key: "CESIUM", text: "CESIUM", value: "CESIUM" },
  { key: "BARIUM", text: "BARIUM", value: "BARIUM" },
  { key: "LANTHANUM", text: "LANTHANUM", value: "LANTHANUM" },
  { key: "CERIUM", text: "CERIUM", value: "CERIUM" },
  { key: "PRASEODYMIUM", text: "PRASEODYMIUM", value: "PRASEODYMIUM" },
  { key: "NEODYMIUM", text: "NEODYMIUM", value: "NEODYMIUM" },
  { key: "PROMETHIUM", text: "PROMETHIUM", value: "PROMETHIUM" },
  { key: "SAMARIUM", text: "SAMARIUM", value: "SAMARIUM" },
  { key: "EUROPIUM", text: "EUROPIUM", value: "EUROPIUM" },
  { key: "GADOLINIUM", text: "GADOLINIUM", value: "GADOLINIUM" },
  { key: "TERBIUM", text: "TERBIUM", value: "TERBIUM" },
  { key: "DYSPROSIUM", text: "DYSPROSIUM", value: "DYSPROSIUM" },
  { key: "HOLMIUM", text: "HOLMIUM", value: "HOLMIUM" },
  { key: "ERBIUM", text: "ERBIUM", value: "ERBIUM" },
  { key: "THULIUM", text: "THULIUM", value: "THULIUM" },
  { key: "YTTERBIUM", text: "YTTERBIUM", value: "YTTERBIUM" },
  { key: "LUTETIUM", text: "LUTETIUM", value: "LUTETIUM" },
  { key: "HAFNIUM", text: "HAFNIUM", value: "HAFNIUM" },
  { key: "TANTALUM", text: "TANTALUM", value: "TANTALUM" },
  { key: "TUNGSTEN", text: "TUNGSTEN", value: "TUNGSTEN" },
  { key: "RHENIUM", text: "RHENIUM", value: "RHENIUM" },
  { key: "OSMIUM", text: "OSMIUM", value: "OSMIUM" },
  { key: "IRIDIUM", text: "IRIDIUM", value: "IRIDIUM" },
  { key: "PLATINUM", text: "PLATINUM", value: "PLATINUM" },
  { key: "GOLD", text: "GOLD", value: "GOLD" },
  { key: "MERCURY", text: "MERCURY", value: "MERCURY" },
  { key: "THALLIUM", text: "THALLIUM", value: "THALLIUM" },
  { key: "LEAD", text: "LEAD", value: "LEAD" },
  { key: "BISMUTH", text: "BISMUTH", value: "BISMUTH" },
  { key: "POLONIUM", text: "POLONIUM", value: "POLONIUM" },
  { key: "ASTATINE", text: "ASTATINE", value: "ASTATINE" },
  { key: "RADON", text: "RADON", value: "RADON" },
  { key: "FRANCIUM", text: "FRANCIUM", value: "FRANCIUM" },
  { key: "RADIUM", text: "RADIUM", value: "RADIUM" },
  { key: "ACTINIUM", text: "ACTINIUM", value: "ACTINIUM" },
  { key: "THORIUM", text: "THORIUM", value: "THORIUM" },
  { key: "PROTACTINIUM", text: "PROTACTINIUM", value: "PROTACTINIUM" },
  { key: "URANIUM", text: "URANIUM", value: "URANIUM" },
  { key: "NEPTUNIUM", text: "NEPTUNIUM", value: "NEPTUNIUM" },
  { key: "PLUTONIUM", text: "PLUTONIUM", value: "PLUTONIUM" },
  { key: "AMERICIUM", text: "AMERICIUM", value: "AMERICIUM" },
  { key: "CURIUM", text: "CURIUM", value: "CURIUM" },
  { key: "BERKELIUM", text: "BERKELIUM", value: "BERKELIUM" },
  { key: "CALIFORNIUM", text: "CALIFORNIUM", value: "CALIFORNIUM" },
  { key: "EINSTEINIUM", text: "EINSTEINIUM", value: "EINSTEINIUM" },
  { key: "FERMIUM", text: "FERMIUM", value: "FERMIUM" },
  { key: "MENDELEVIUM", text: "MENDELEVIUM", value: "MENDELEVIUM" },
  { key: "NOBELIUM", text: "NOBELIUM", value: "NOBELIUM" },
  { key: "LAWRENCIUM", text: "LAWRENCIUM", value: "LAWRENCIUM" },
  { key: "RUTHERFORDIUM", text: "RUTHERFORDIUM", value: "RUTHERFORDIUM" },
  { key: "DUBNIUM", text: "DUBNIUM", value: "DUBNIUM" },
  { key: "SEABORGIUM", text: "SEABORGIUM", value: "SEABORGIUM" },
  { key: "BOHRIUM", text: "BOHRIUM", value: "BOHRIUM" },
  { key: "HASSIUM", text: "HASSIUM", value: "HASSIUM" },
  { key: "MEITNERIUM", text: "MEITNERIUM", value: "MEITNERIUM" },
  { key: "UNUNNILIUM", text: "UNUNNILIUM", value: "UNUNNILIUM" },
  { key: "UNUNUNIUM", text: "UNUNUNIUM", value: "UNUNUNIUM" },
  { key: "UNUNBIUM", text: "UNUNBIUM", value: "UNUNBIUM" }
];

const MaterialSearchSelection = () => (
  <Dropdown
    placeholder="Select Material"
    fluid
    search
    selection
    options={materialOptions}
    size="mini"
  />
);

export default MaterialSearchSelection;
